### ISSUE TITLE
一些小问题，麻烦指教

### ISSUE THREAD

**Issue by cokePanda** [ppoffice/hexo-theme-hueman#11]
![screen shot 2015-03-11 at 9 34 45 pm](https://cloud.githubusercontent.com/assets/11265761/6597600/cd8caa5a-c838-11e4-8e34-f433ed67175b.jpg)
如图，一些标题好像显示不太正确
还有，可以增加热门文章，热门讨论，相关文章等么？
谢谢

**Comment by ppoffice** [comment]
请在hexo根目录中的_config.yml加入语言项`language`。
```yml
# Site
title: Hueman
subtitle: Inspire and empower.
description:
author: PPOffice
language: en #Edit this
timezone:
```
