### ISSUE TITLE
Adding an extra menu items Travel, gives me index.travel on the page

### ISSUE THREAD

**Issue by eriksteinebach** [ppoffice/hexo-theme-hueman#112]
Hello,

I am using the hueman theme (great btw! Thanks!), but I think I found a bug. I want to add an extra menu item: 

```
# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about/index.html
    Travel: http://www.***.nl
```

But on the page this renders as:
![capture_hueman](https://cloud.githubusercontent.com/assets/5765891/15270916/96d4f84e-19f6-11e6-9f0b-088cff0f4d1f.JPG)

Of course I would have expected the word Travel as the name of the link. Am I doing something wrong? Or is this a bug?
