### ISSUE TITLE
How did you convert css to stylus for highlight.js theme ?

### ISSUE THREAD

**Issue by shark-oxi** [ppoffice/hexo-theme-hueman#114]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully;
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

Hello,

If I pick the first highlight theme named **agate**,

The highlight.js css
```css
/*!
 * Agate by Taufik Nurrohman <https://github.com/tovic>
 * ----------------------------------------------------
 *
 * #ade5fc
 * #a2fca2
 * #c6b4f0
 * #d36363
 * #fcc28c
 * #fc9b9b
 * #ffa
 * #fff
 * #333
 * #62c8f3
 * #888
 *
 */

.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: #333;
  color: white;
}

.hljs-name,
.hljs-strong {
  font-weight: bold;
}

.hljs-code,
.hljs-emphasis {
  font-style: italic;
}

.hljs-tag {
  color: #62c8f3;
}

.hljs-variable,
.hljs-template-variable,
.hljs-selector-id,
.hljs-selector-class {
  color: #ade5fc;
}

.hljs-string,
.hljs-bullet {
  color: #a2fca2;
}

.hljs-type,
.hljs-title,
.hljs-section,
.hljs-attribute,
.hljs-quote,
.hljs-built_in,
.hljs-builtin-name {
  color: #ffa;
}

.hljs-number,
.hljs-symbol,
.hljs-bullet {
  color: #d36363;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal {
  color: #fcc28c;
}

.hljs-comment,
.hljs-deletion,
.hljs-code {
  color: #888;
}

.hljs-regexp,
.hljs-link {
  color: #c6b4f0;
}

.hljs-meta {
  color: #fc9b9b;
}

.hljs-deletion {
  background-color: #fc9b9b;
  color: #333;
}

.hljs-addition {
  background-color: #a2fca2;
  color: #333;
}

.hljs a {
  color: inherit;
}

.hljs a:focus,
.hljs a:hover {
  color: inherit;
  text-decoration: underline;
}
```

The stylus css you embed : 
```stylus
/*!
 * Agate by Taufik Nurrohman <https://github.com/tovic>
 * ----------------------------------------------------
 *
 * #ade5fc
 * #a2fca2
 * #c6b4f0
 * #d36363
 * #fcc28c
 * #fc9b9b
 * #ffa
 * #fff
 * #333
 * #62c8f3
 * #888
 *
 */

.highlight
    color: white
    background: #333
    .code
        .name,
        .strong
            font-weight: bold

        .code,
        .emphasis
            font-style: italic

        .tag
            color: #62c8f3

        .variable,
        .template-variable,
        .selector-id,
        .selector-class
            color: #ade5fc

        .string,
        .bullet
            color: #a2fca2

        .type,
        .title,
        .section,
        .attribute,
        .quote,
        .built_in,
        .builtin-name
            color: #ffa

        .number,
        .symbol,
        .bullet
            color: #d36363

        .keyword,
        .selector-tag,
        .literal
            color: #fcc28c

        .comment,
        .deletion,
        .code
            color: #888

        .regexp,
        .link
            color: #c6b4f0

        .meta
            color: #fc9b9b

        .deletion
            background-color: #fc9b9b
            color: #333

        .addition
            background-color: #a2fca2
            color: #333

        .highlight a
            color: inherit

        .highlight a:focus,
        .highlight a:hover
            color: inherit
            text-decoration: underline
```

If I use a css to stylus converter I can get : 
```stylus
.hljs
  display block
  overflow-x auto
  padding 0.5em
  background #333
  color white
  a
    color inherit

.hljs-name,
.hljs-strong
  font-weight bold

.hljs-code,
.hljs-emphasis
  font-style italic

.hljs-tag
  color #62c8f3

.hljs-variable,
.hljs-template-variable,
.hljs-selector-id,
.hljs-selector-class
  color #ade5fc

.hljs-string,
.hljs-bullet
  color #a2fca2

.hljs-type,
.hljs-title,
.hljs-section,
.hljs-attribute,
.hljs-quote,
.hljs-built_in,
.hljs-builtin-name
  color #ffa

.hljs-number,
.hljs-symbol,
.hljs-bullet
  color #d36363

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal
  color #fcc28c

.hljs-comment,
.hljs-deletion,
.hljs-code
  color #888

.hljs-regexp,
.hljs-link
  color #c6b4f0

.hljs-meta
  color #fc9b9b

.hljs-deletion
  background-color #fc9b9b
  color #333

.hljs-addition
  background-color #a2fca2
  color #333

.hljs a:focus,
.hljs a:hover
  color inherit
  text-decoration underline
```

But I can see class are not the same and your stylus is more nested.

So how did you convert the original css to this stylus ? By hand or with a tool ?

Because the version of highlight.js you embed is not up to date and I wanted to help you to update it.
