### ISSUE TITLE
Custom Menu items don't look right

### ISSUE THREAD

**Issue by maxirus** [ppoffice/hexo-theme-hueman#203]
When adding custom menu items, as the docs suggest [here](https://github.com/ppoffice/hexo-theme-hueman/wiki/Theme#menu), this line reformats it toLower and prefixes it with 'index.'; why? Am I missing something?

It seems this should be:
``<a class="main-nav-list-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>``

ie. The docs say I can do:
```
menu:
    Home: /
    About: /about/index.html
    Github: https://github.com/
```

But this results in the menu bar getting ``index.github`` as the link/button.

https://github.com/ppoffice/hexo-theme-hueman/blob/87ac098db5c842010816d48dd5fc5dbd620df362/layout/common/header.ejs#L29
