### ISSUE TITLE
insight Cannot GET /content.json

### ISSUE THREAD

**Issue by tinohean** [ppoffice/hexo-theme-hueman#213]
搜索无效，配置如下
_config.yml

```
# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Se
arch
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: tru
e, false
```
npm ls
hexo-theme-hueman@0.2.1 /alpha/themes/hueman
└─┬ hexo-generator-json-content@3.0.1
  ├─┬ hexo-util@0.6.3
  │ ├── bluebird@3.5.1
  │ ├─┬ camel-case@3.0.0
  │ │ ├─┬ no-case@2.3.2
  │ │ │ └── lower-case@1.1.4
  │ │ └── upper-case@1.1.3
  │ ├─┬ cross-spawn@4.0.2
  │ │ ├─┬ lru-cache@4.1.2
  │ │ │ ├── pseudomap@1.0.2
  │ │ │ └── yallist@2.1.2
  │ │ └─┬ which@1.3.0
  │ │   └── isexe@2.0.0
  │ ├── highlight.js@9.12.0
  │ ├── html-entities@1.2.1
  │ └── striptags@2.2.1
  ├─┬ keyword-extractor@0.0.15
  │ ├── underscore@1.7.0
  │ └── underscore.string@2.3.3
  └── moment@2.22.0

全目录搜索也找不到content.json... 求助
