### ISSUE TITLE
menu problem

### ISSUE THREAD

**Issue by BigBigLeechee** [ppoffice/hexo-theme-hueman#214]
## what causes this problem?

> the menu config just like this

```yml

menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    # Categories: 
    Technology: /technology/
    About: /about/index.html
    Gallery: /gallery/index.html
    GitHub: https://github.com
```

> while show  such like the following

![image](https://user-images.githubusercontent.com/26338665/38251097-13c12e44-3783-11e8-8359-52e253577490.png)
