### ISSUE TITLE
about the menu bar 

### ISSUE THREAD

**Issue by smartzer** [ppoffice/hexo-theme-hueman#227]
I created my own configuration file(_config.yml) and configure the menu just like this :

```
menu:
    Home: /hexo-theme-hueman/
    Life: https://github.com/smartzer
    Code: /code
    City: /city
```
but when i use ` hexo clean`,` hexo g s`, I got the home page is like this:

![1](https://user-images.githubusercontent.com/29965801/42255037-4c0b748a-7f7c-11e8-9e40-5a1b1754236c.JPG)

I don't konw where the `index` prefix in front of my menus....
I thought maybe some themes conflict ，but when i delete the other themes ，it seems not worked.

Thank you for solving my problem！
sincerely!
