### ISSUE TITLE
关于自定义菜单栏

### ISSUE THREAD

**Issue by qimingyudaowenti** [ppoffice/hexo-theme-hueman#253]
我将菜单修改如下：
```
menu:
    Home: /home.html
    Member: /member.html
    Research: /
    Achievement: /achievement.html
```
效果如下：
![menu](https://user-images.githubusercontent.com/17612199/53340290-9b250f00-3943-11e9-93dd-1b7058a5edb6.png)

这样可以将文章显示在Research（研究成果）菜单下。但我想在进入网站的时候直接显示`.../home.html`，该怎样做呢？而且其他三个增加的菜单项都无法正常高亮，该如何修改？
可不可以把下图中：
![repeat](https://user-images.githubusercontent.com/17612199/53340818-e12ea280-3944-11e9-8f05-f27f81552b59.png)
第二行重复的`title`去掉？

希望得到解答，十分感谢！

**Comment by ppoffice** [comment]
@qimingyudaowenti 
直接转到home.html 可以在http服务器中设置重定向，如果你使用GitHub这种托管服务的话估计不行了
另外你把你menu中链接后面的`.html`去掉看看菜单项高亮正不正常
最后把下面这几行注释掉就可以去掉标题了：https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/common/article.ejs#L3-L7

**Comment by qimingyudaowenti** [comment]
> 另外你把你menu中链接后面的`.html`去掉看看菜单项高亮正不正常

改成了这样：
```
menu:
    Home: /home
    Member: /member
    Research: /
    Achievement: /achievement
```
url变成了`http://localhost:5000/achievement/`，网页打不开，提示：
```
http://localhost:5000/achievement/
```
请问还有别的方法吗？:joy:
