### ISSUE TITLE
cant not insert categories in the menu

### ISSUE THREAD

**Issue by linnanCHEN** [ppoffice/hexo-theme-hueman#59]
could you explain a little bit how to insert categories in the menu of the header ?
i ve tried several times but fail to envision the categories in the menu.

**Comment by ppoffice** [comment]
Just add `Categories:` to your _config.yml:
```
menu:
  Home: /
  Categories:
  About: /about/index.html
```

**Comment by linnanCHEN** [comment]
this is my setting in the _config.yml:
```
menu:

  Home:
  Archives: /archives
  Reading: /reading
  Categories: /categories
  About: 关于 

```
I did not forget to create folder as it is mentioned below
> you can create `tags` and `categories` folders in `../source`.
>And create a `index.md` file in each of them.
>set `front-matter`as
>layout: tags (or categories)
>title: tags (or categories)

but i can see nothing but a black menu....
